---
title: "Mobilisation of epicardial progenitors at the origin of Atrial Fibrillation"
output: 
  html_document: 
    self_contained: no
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Abstract

Atrial fibrillation (AF) is a consequence of an atrial cardiomyopathy that affects 1% of the population and  up to 10% of elderly subjects. Often associated with co-morbidity factors (heart failure, mitral valve pathology, diabetes, high blood pressure or obesity), the clinical symptoms are severe heart rhythm disorders. The risk of initiation of FA is greatly increased by the presence of adipose tissue enveloping the heart. AF substrate is composed of both adipose and fibroblastic tissues and its extracellular matrix (fibrosis) that accumulate within the atria.

The project addressed the question of the cell origin of both adipose and fibroblastics tissues. 

The single cell-RNA seq approach performed from epicardial  cells from healthy  rat (SHAM2) or rats with a cardiomyopathy  (IDM) uncovered that a subset of epicardial cells and  epicardial-derived cells which underwent epithelia-to-mesenchymal transition give rise to either adipocytes or fibroblasts responding to ANP ( released by atrial stretching)  or Angiotensin 2, ( an arterial tension modulator),respectively.   

Circ Res. 2020 Mar 16. CIRCRESAHA.119.316251 [https://www.ahajournals.org/doi/10.1161/CIRCRESAHA.119.316251]


`r shiny::includeHTML(system.file("extdata", "generalSCHNAPPs.html",package = "SCHNAPPs"))`

<!-----
`r shiny::includeHTML("inst/extdata/generalSCHNAPPs.html")`
----->
