defaultValues[["gsSelectedGenesMod-showAllCells"]] =  FALSE 
defaultValues[["gsRMGenesMod-showAllCells"]] =  FALSE 
defaultValues[["cellSelectionMod-showAllCells"]] =  FALSE 
defaultValues[["normalizationResult-showAllCells"]] =  FALSE 
defaultValues[["coE_SOM_dataInput-Mod_clusterPP"]] =  "dbCluster" 
defaultValues[["coE_SOM_dataInput-Mod_PPGrp"]] =  1 
defaultValues[["coE_heatmapSOM-sortingCols"]] =  "dendrogram" 
defaultValues[["coE_heatmapSOM-normRow"]] =  "none" 
defaultValues[["coE_heatmapSOM-ColNames"]] =  "sampleNames" 
defaultValues[["coE_heatmapSOM-orderNames"]] =  "" 
defaultValues[["coE_heatmapSOM-heatmapMinMaxValue"]] =  c(-1,1)
# defaultValues[["coE_heatmapSOM-heatmapWidth"]] =  800 
# defaultValues[["coE_heatmapSOM-heatmapHeight"]] =  300 
defaultValues[["coE_heatmapSOM-colPal"]] =  "none" 
defaultValues[["scorpiusHeatmapPlotModule-sortingCols"]] =  "dendrogram" 
defaultValues[["scorpiusHeatmapPlotModule-normRow"]] =  "none" 
defaultValues[["scorpiusHeatmapPlotModule-ColNames"]] =  "sampleNames" 
defaultValues[["scorpiusHeatmapPlotModule-orderNames"]] =   ""
defaultValues[["scorpiusHeatmapPlotModule-heatmapMinMaxValue"]] =  c(-1,1) 
# defaultValues[["scorpiusHeatmapPlotModule-heatmapWidth"]] =  800 
# defaultValues[["scorpiusHeatmapPlotModule-heatmapHeight"]] =  300 
defaultValues[["scorpiusHeatmapPlotModule-colPal"]] =  "none" 
defaultValues[["scorpiusTableMod-showAllCells"]] =  FALSE 
defaultValues[["elpiHeatmapPlotModule-sortingCols"]] =  "dendrogram" 
defaultValues[["elpiHeatmapPlotModule-normRow"]] =  "none" 
defaultValues[["elpiHeatmapPlotModule-ColNames"]] =  "sampleNames" 
defaultValues[["elpiHeatmapPlotModule-orderNames"]] =   ""
defaultValues[["elpiHeatmapPlotModule-heatmapMinMaxValue"]] =   c(-1,1)
# defaultValues[["elpiHeatmapPlotModule-heatmapWidth"]] =  800 
# defaultValues[["elpiHeatmapPlotModule-heatmapHeight"]] =  300 
defaultValues[["elpiHeatmapPlotModule-colPal"]] =  "none" 
defaultValues[["elpiTableMod-showAllCells"]] =  FALSE 
defaultValues[["coExpHeatmapModule-sortingCols"]] =  "dendrogram" 
defaultValues[["coExpHeatmapModule-normRow"]] =  "none" 
defaultValues[["coExpHeatmapModule-ColNames"]] =  "sampleNames" 
defaultValues[["coExpHeatmapModule-orderNames"]] =   ""
defaultValues[["coExpHeatmapModule-heatmapMinMaxValue"]] =    c(-1,1)
# defaultValues[["coExpHeatmapModule-heatmapWidth"]] =  800 
# defaultValues[["coExpHeatmapModule-heatmapHeight"]] =  300 
defaultValues[["coExpHeatmapModule-colPal"]] =  "none" 
defaultValues[["coE_selected-geneIds"]] =   ""
defaultValues[["coE_selected-geneIds2"]] =   ""
defaultValues[["coE_selected-dimension_x"]] =  "tsne1" 
defaultValues[["coE_selected-dimension_y"]] =  "tsne2" 
defaultValues[["coE_selected-dimension_col"]] =  "sampleNames" 
defaultValues[["coE_selected-logX"]] =  FALSE 
defaultValues[["coE_selected-logY"]] =  FALSE 
defaultValues[["coE_selected-divideXBy"]] =  "None" 
defaultValues[["coE_selected-divideYBy"]] =  "None" 
defaultValues[["coE_selected-groupNames"]] =  plot 
defaultValues[["coE_selected-showCells"]] =  FALSE 
defaultValues[["coE_heatmapSelectedModule-sortingCols"]] =  "dendrogram" 
defaultValues[["coE_heatmapSelectedModule-normRow"]] =  "none" 
defaultValues[["coE_heatmapSelectedModule-ColNames"]] =  "sampleNames" 
defaultValues[["coE_heatmapSelectedModule-orderNames"]] =   ""
defaultValues[["coE_heatmapSelectedModule-heatmapMinMaxValue"]] =    c(-1,1)
# defaultValues[["coE_heatmapSelectedModule-heatmapWidth"]] =  800 
# defaultValues[["coE_heatmapSelectedModule-heatmapHeight"]] =  300 
defaultValues[["coE_heatmapSelectedModule-colPal"]] =  "none" 
defaultValues[["coEtgMinExpr"]] =  1 
defaultValues[["coEtgPerc"]] =  60 
defaultValues[["coE_topExpGenes-showAllCells"]] =  FALSE 
defaultValues[["coE_topCCGenes-showAllCells"]] =  FALSE 
defaultValues[["coE_showPermutations"]] =  FALSE 
defaultValues[["coE_geneGrpVioIds"]] =  "CD52, S100A9, S100A4" 
defaultValues[["coE_dimension_xVioiGrp"]] =  "dbCluster" 
defaultValues[["coEminMaxExpr"]] =  c(-1,1) 
defaultValues[["coE_geneGrpVioIds2"]] =  "CD52, S100A9, S100A4" 
defaultValues[["coE_dimension_xVioiGrp2"]] =  "dbCluster" 
defaultValues[["coEminMaxExpr2"]] =  c(-1,1) 
defaultValues[["alluiv1"]] =  "notyet" 
defaultValues[["alluiv2"]] =  "notyet" 
defaultValues[["DE_Exp_dataInput-Mod_clusterPP"]] =  "dbCluster" 
defaultValues[["DE_Exp_dataInput-Mod_PPGrp"]] =  1 
defaultValues[["DE_gene_id"]] =  "itgae" 
defaultValues[["DE_expclusters-geneIds"]] =   
defaultValues[["DE_expclusters-geneIds2"]] =   
defaultValues[["DE_expclusters-dimension_x"]] =  "tsne1" 
defaultValues[["DE_expclusters-dimension_y"]] =  "tsne2" 
defaultValues[["DE_expclusters-dimension_col"]] =  "sampleNames" 
defaultValues[["DE_expclusters-logX"]] =  FALSE 
defaultValues[["DE_expclusters-logY"]] =  FALSE 
defaultValues[["DE_expclusters-divideXBy"]] =  "None" 
defaultValues[["DE_expclusters-divideYBy"]] =  "None" 
defaultValues[["DE_expclusters-groupNames"]] =  "plot" 
defaultValues[["DE_expclusters-showCells"]] =  FALSE 
defaultValues[["DE_PanelPlotCellSelection-Mod_clusterPP"]] =  "dbCluster" 
defaultValues[["DE_PanelPlotCellSelection-Mod_PPGrp"]] =  1 
defaultValues[["DE_dim_x"]] =  "tsne1" 
defaultValues[["DE_dim_y"]] =  "tsne2" 
defaultValues[["DE_panelplotSameScale"]] =  TRUE 
defaultValues[["DE_nCol"]] =  4 
defaultValues[["DE_panelplotids"]] =  "CD52, S100A9, S100A4" 
defaultValues[["oldPrj"]] =  "not yet" 
defaultValues[["newPrj"]] =   ""
defaultValues[["delPrj"]] =  "notyet" 
defaultValues[["gQC_projCombTableMod-showAllCells"]] =  FALSE 
defaultValues[["gQC_tsnePerplexity"]] =  30 
defaultValues[["gQC_tsneTheta"]] =  0.5 
defaultValues[["gQC_tsneSeed"]] =  1 
defaultValues[["gQC_dim3D_x"]] =  "tsne1" 
defaultValues[["gQC_dim3D_y"]] =  "tsne2" 
defaultValues[["gQC_dim3D_z"]] =  "tsne3" 
defaultValues[["gQC_col3D"]] =  "sampleNames" 
defaultValues[["gQC_projectionTableMod-showAllCells"]] =  FALSE 
defaultValues[["gQC_um_n_neighbors"]] =  15 
defaultValues[["gQC_um_n_components"]] =  2 
defaultValues[["gQC_um_spread"]] =  1 
defaultValues[["gQC_um_local_connectivity"]] =  1 
defaultValues[["gQC_um_randSeed"]] =  1 
defaultValues[["gQC_um_init"]] =  "spectral" 
defaultValues[["gQC_um_negative_sample_rate"]] =  5 
defaultValues[["gQC_um_min_dist"]] =  0.01 
defaultValues[["gQC_um_metric"]] =  "euclidean" 
defaultValues[["gQC_um_set_op_mix_ratio"]] =  1 
defaultValues[["gQC_um_n_epochs"]] =  200 
defaultValues[["gQC_um_bandwidth"]] =  1 
defaultValues[["gQC_umap_main-geneIds"]] =   ""
defaultValues[["gQC_umap_main-geneIds2"]] =   ""
defaultValues[["gQC_umap_main-dimension_x"]] =  "UMAP1" 
defaultValues[["gQC_umap_main-dimension_y"]] =  "UMAP2" 
defaultValues[["gQC_umap_main-dimension_col"]] =  "dbCluster" 
defaultValues[["gQC_umap_main-logX"]] =  FALSE 
defaultValues[["gQC_umap_main-logY"]] =  FALSE 
defaultValues[["gQC_umap_main-divideXBy"]] =  "None" 
defaultValues[["gQC_umap_main-divideYBy"]] =  "None" 
defaultValues[["gQC_umap_main-groupNames"]] =  plot 
defaultValues[["gQC_umap_main-showCells"]] =  FALSE 
defaultValues[["sCA_dataInput-Mod_clusterPP"]] =  "dbCluster" 
defaultValues[["sCA_dataInput-Mod_PPGrp"]] =  1 
defaultValues[["sCA_subscluster_x1"]] =  "tsne1" 
defaultValues[["sCA_subscluster_y1"]] =  "tsne2" 
defaultValues[["sCA_dgeRadioButton"]] =  "none" 
defaultValues[["sCA_volc_effectLimit"]] =  1 
defaultValues[["sCA_volc_pval"]] =  5 
defaultValues[["sCA_dgeTable-showAllCells"]] =  FALSE 
defaultValues[["gsSelectedGenesMod-showAllCells"]] =  FALSE 
defaultValues[["gsRMGenesMod-showAllCells"]] =  FALSE 
